#12 Dismiss employee option
dmytroshchotkin/TruckTir pull request #14
Opened 2023-11-27 21:33 UTC by a-v-dubr

- добавлен фильтр по активным / уволенным / всем сотрудникам
- добавлено увольнение (только для админов)

2023-12-12 03:21 UTC, dmytroshchotkin requested changes

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee != null)
есть вариант когда _editEmployee может быть null?
И я тебе уже говорил как проверку на null делать правильно.

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            if (_employeeEditingInProcess)
Зачем здесь это условие?
Во-первых метод FillTheForm чётко выполняет то что написано в его названии. Если такая проверка нужна, она должна быть на уровень выше в месте вызова. Но я всё-равно не пойму зачем нам эта проверка даже на уровень выше.

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                    birthDateTimePicker.Visible = false;
а тут что происходит?

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                if (employee.DismissalDate != default)
Так, ну как минимум визуально это решение выглядит очень плохо. Используй  может локальный метод с адекватным названием. 
Ну для начала скажи мне почему у нас тут такая странная логика?

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            passwordAgainStarLabel.Enabled = false;
чисто визуальное замечание. Группировка и/или последовательность должна быть в функциональном порядке, а не в я не знаю каком.
Т.е. вот так:
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/f15ed5c6-5173-43a3-94bc-79d5ab373216)

2023-12-12 03:21 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +        private void DisableAccessControls()
не Access а Credentials

2023-12-12 22:42 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +        private void DisableAccessControls()
переименовала

2023-12-12 22:43 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            passwordAgainStarLabel.Enabled = false;
сделала как на твоём скрине

2023-12-12 22:44 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                if (employee.DismissalDate != default)
создала метод IsEmployeeDismissed.

если сотрудник уволен, показываем дату увольнения и деактивируем элементы управления, связанные с доступом (выбор уровня доступа, ввод логина и пароля), чтобы форма не запрашивала их обязательный ввод

2023-12-12 22:45 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                    birthDateTimePicker.Visible = false;
если сотрудник уволен, блокируем возможность менять дату рождения, скрывая DateTimePicker, и выводим существующую дату

2023-12-12 22:46 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee != null)
ты прав, не может быть такого. удалила везде.
(это были остатки предыдущих изменений, которые я в итоге не использовала. в след. раз буду делать такие вещи в отдельной ветке)

проверка is not null недоступна, заменила !=null на null conditional operator 
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/5831621d-522c-4c46-801c-2d92f379bc10)

2023-12-12 22:48 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            if (_employeeEditingInProcess)
лишнее условие, убрала

2023-12-12 23:56 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee != null)
понял)

2023-12-14 18:58 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                if (employee.DismissalDate != default)
добавила в Employee метод IsDismissed, метод удалила

2023-12-14 19:34 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            if (_employeeEditingInProcess)
добавила отдельные методы для элементов управления, которые применяются в FillTheForm для уволенных и активных сотрудников

2023-12-16 11:12 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                    birthDateTimePicker.Visible = false;
добавила отдельные методы для элементов управления, которые применяются в FillTheForm для уволенных и активных сотрудников

2023-12-16 19:32 UTC, dmytroshchotkin requested changes

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
Зачем ты это тут поменяла?

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                        {
пробелы удали

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                    if (employee.DismissalDate < DateTime.Now)
почему внезапно такая проверка? Ты же в другом месте по другому проверяешь. У нас нельзя будущим числом увольнять, поэтому всё что отлично от default значит уволен.

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                    if (employee.DismissalDate < DateTime.Now)
А вообще вынеси метод 'IsEmployeeDismissed' в сам класс Employee

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
Не нравится мне теперь такой подход.
Не нужен нам тут exception.
поменяй First() на FirstOrDefault() и избавься от try-catch и обрабатывай нормально.

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    EmployeeListBox.DataSource = GetActiveEmployees();
баг в этом месте.
Reproduction steps:
1) выбери оба чекбокса
2) заблокируй юзера

AR (actual result): два чекбокса выбраны, но по факту только активные юзеры отображаются
ER (expected result): если оба чекбокса выбрано, то список можно не обновлять, только заблокированный объект в этом списке должен быть обновлён.

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                if (_selectedEmployee.DismissalDate != default)
тут тоже используй 'employee.IsDismissed' св-во

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +            if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
создай у Employee auto-property 'IsAdmin' и используй его для проверки

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    }
вынеси весь этот if-else в private метод с говорящим названием

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +
не оставляй пустые линии между if и else if

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    EmployeeListBox.Visible = true;
зачем тут опять присваивать true если это уже сделано выше?

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                }
весь этот монструозный if-elseif-elseif должен быть вынесен в отдельный метод. а тут это должно выглядеть так. 
`EmployeeListBox.DataSource = GetEmployees(ActiveEmployeesCheckBox.Checked, InactiveEmployeesCheckBox.Checked);`

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        /// Заполняет ListBox сотрудниками выбранного типа; если выбраны оба чекбокса, грузит всех; если не выбран ни один, грузит только Активных
Это пример плохого коммента. Ибо он описывает просто содержащий код. А код поменялся и больше этот коммент не актуален. Коммент может иметь смысл если он раскрывает суть или задумку метода. 
В данном случае хэндлер события не имеет смысл помечать комментом, т.к. его суть в том чтобы быть хэндлером.

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            }
Честно, не нравится мне эта куча методов. Я уверен, что тут можно обойтись одним методом который будет принимать параметры.
Но это ладно

2023-12-16 19:32 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            }
А вот что не ладно, так это то что у нас в методе который называется 'FillTheForm' есть функционал который помимо заполнения, также делает другие манипуляции с элементами UI, типа Visible и Enable.
Это должно быть вынесено в отдельный метод и должно вызываться на уровень выше.

2023-12-19 15:21 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                        {
убрала. 
оставила в этом pr'е, нужно ли переносить в другой? думала про Code style changes, но тут не совсем про code style

2023-12-19 15:24 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
в предыдущем варианте, если у редактируемого сотрудника менялось право доступа с Админа на Обычный, обновление пропускалось (т.к. переменная employee при проверке в блоке if имеет AccessLayer == "Обычный"). сейчас разрешаем редактировать все поля (кроме логина и пароля у админов), если редактор является админом
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/2b5857d8-d10f-4742-b240-deafac277a5c)

2023-12-19 15:24 UTC, a-v-dubr commented on PartsApp/AuthorizationForm.cs
> +                    if (employee.DismissalDate < DateTime.Now)
добавила свойство

2023-12-19 15:25 UTC, a-v-dubr commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
заменила на while

2023-12-19 15:25 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    EmployeeListBox.DataSource = GetActiveEmployees();
исправила

2023-12-19 15:26 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +
исправила в коммите с удалёнными пробелами после { и }

2023-12-19 15:26 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                if (_selectedEmployee.DismissalDate != default)
исправила

2023-12-19 15:26 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +            if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
добавила свойство

2023-12-19 15:27 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    }
добавила метод

2023-12-19 15:28 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    EmployeeListBox.Visible = true;
осталось по ошибке, удалила

2023-12-19 15:30 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                }
добавила метод, настройки visibility вынесла отдельно

2023-12-19 15:31 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        /// Заполняет ListBox сотрудниками выбранного типа; если выбраны оба чекбокса, грузит всех; если не выбран ни один, грузит только Активных
удалила комментарий, больше такие писать не буду)

2023-12-19 15:33 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            }
исправила. в FillTheForm только заполнение полей, отдельно устанавливается visibility и отдельно - доступность credentials для уволенных и активных

2023-12-20 16:26 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
Такс, ладно, вроде логично.
Единственно у нас тут для этого if нет его else.
Что происходит если в этом методе не админ пытается редактировать не себя?

2023-12-20 16:26 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                        {
Какой другой? Пока ещё у тебя не должно быть никакого другого.

2023-12-20 16:35 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
Это что за ужас? Ты должна 1000 раз подумать в принципе перед тем как while(true) куда-либо добавлять.
Зачем тебе в принципе тут цикл понадобился? Это что за абсурд? Особенно с учётом того что ты всё-равно выходишь из этого цикла всегда в первой итерации.
Не ручаюсь за правильность. Но что-то подобное я от тебя хотел
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/800285f5-b65c-4eed-855f-08b006292825)

2023-12-20 16:49 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                return null;
обрати внимание на warning-и в этом методе

2023-12-20 16:49 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            }
так-то лучше

2023-12-20 16:52 UTC, dmytroshchotkin requested changes

2023-12-20 16:52 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
>          private bool CheckAllConditionsForWrightValues()
что такое 'wright'? :)

2023-12-20 18:44 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
не админ не может редактировать других пользователей (в предшествующей форме для него не отобразится соотв. меню). так что условие IsAdmin внутри этого метода совсем можно удалить, наверно
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/c02b3c80-a699-4b75-9b55-7a7a0fb3a959)

2023-12-20 18:44 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                        {
ок

2023-12-20 18:48 UTC, a-v-dubr commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
исправила. это и правда было очень тупо)

2023-12-20 20:21 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
>          private bool CheckAllConditionsForWrightValues()
переименовала в IsRequiredDataFilledCorrectly

2023-12-20 20:21 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                return null;
внесла правки (оптимизировать bool и не возвращать null)

2023-12-21 18:10 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
такой вопрос, у нас на этом участке в одном случае (else) есть явное присвоение в пер-ную и вызов this.close, а в другом нет.
оно нормально тут работает?
мне кажется тут надо подход унифицировать

2023-12-21 18:13 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
вот значит этого хороший кейс для комментария (если нет способа сделать код более понятным)

2023-12-21 18:27 UTC, dmytroshchotkin requested changes

2023-12-21 18:27 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private List<Employee> GetEmployees(bool isActiveEmployeesCheckBoxChecked, bool isInactiveEmployeesCheckBoxChecked)
Ну блин, это же уже приватный метод, который, в идеале, ничего не знает о контексте своего вызова, т.е. не знает он ничего о чекбоксах никаких. Нельзя разве аргументы метода по-человечески назвать? :)

2023-12-21 18:27 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +            if (isActiveEmployeesCheckBoxChecked)
Этот код очень плохо читабелен.
Вот примерно как это должно выглядеть

![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/b812342d-b556-4456-a48e-d77c6125a673)

2023-12-21 19:44 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +                if (Form1.CurEmployee.AccessLayer == Employee.AccessLayers.Admin.ToDescription())
обновила коммент в строке над if в UpdateEmployee

2023-12-21 19:44 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private List<Employee> GetEmployees(bool isActiveEmployeesCheckBoxChecked, bool isInactiveEmployeesCheckBoxChecked)
переименовала

2023-12-21 19:45 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +            if (isActiveEmployeesCheckBoxChecked)
исправила

2023-12-21 21:28 UTC, a-v-dubr commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
исправила ошибку (при клике Отмена всё равно проверялись поля и при правильном заполнении грузилась основная форма)

2023-12-23 22:39 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private List<Employee> GetEmployees(bool isActiveEmployeesCheckBoxChecked, bool isInactiveEmployeesCheckBoxChecked)
смотри, это не переменная, это аргументы метода. И когда ты начинаешь с 'is' или 'are' это звучит будто ты спрашиваешь "а активные сотрудники выбраны или нет?", в этом случае это либо команда "selectActiveEmployees" либо если вопрос то такого формата "shouldSelectActiveEmployees", но мне императивный (командный) вариант больше нравится.

2023-12-23 22:50 UTC, dmytroshchotkin requested changes

2023-12-23 22:50 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee?.DismissalDate.HasValue == true && _editEmployee.IsDismissed)
А я чёто не пойму, почему это мы опускаем проверки если сотрудник уволен?

2023-12-23 22:53 UTC, dmytroshchotkin commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
зачем нам Close в else? Я уверен его можно просто можно удалить.

2023-12-24 08:55 UTC, a-v-dubr commented on PartsApp/AuthorizationForm.cs
> +                        throw new Exception();
теперь уже нельзя. форма закрывается двумя разными способами: на клике Отмена (+ прерывается загрузка родительской Form1, первый скрин) и на клике Ок при правильном вводе данных (+ продолжается загрузка Form1)
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/e8e8d989-7d18-4d25-a4f8-16e47e3b2c04)
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/ee322f3e-209e-4820-b101-010e1138ec8c)

2023-12-24 09:48 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private List<Employee> GetEmployees(bool isActiveEmployeesCheckBoxChecked, bool isInactiveEmployeesCheckBoxChecked)
переименовала параметры и сам коммит

2023-12-24 10:10 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee?.DismissalDate.HasValue == true && _editEmployee.IsDismissed)
вернула проверки

2023-12-24 10:11 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            if (_editEmployee?.DismissalDate.HasValue == true && _editEmployee.IsDismissed)
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/585d6341-2126-46ef-b068-d7344f9d7763)
установка доступных для редактирования полей запускается и для уволенных, и для активных

2023-12-24 10:50 UTC, a-v-dubr commented
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/e595ce26-24b6-41c9-9f23-e92b5f43d779)
изменила проверку, чтобы в списке сотрудников из EmployeeOperationsForm юзер распознавался как авторизованный

2023-12-24 18:12 UTC, dmytroshchotkin approved these changes

2023-12-24 21:22 UTC, merged