Bug fixes
dmytroshchotkin/TruckTir pull request #17
Opened 2023-12-28 20:37 UTC by a-v-dubr

2024-01-02 16:03 UTC, dmytroshchotkin requested changes

2024-01-02 16:03 UTC, dmytroshchotkin commented on PartsApp/SparePartForm.cs
> +            EnsurePhotoDirectoryCreated();
Нет, не тут это должно быть. Ты вынесла очень узкий concern (проблему) на уровень всего класса.
Есть одно конкретное место где происходит копирование файла в папку, вот там это и должно находиться.
подумай даже с такой стороны, если вдруг ты перенесёшь метод с копированием файла в папку в другой, например статический, класс, и также переиспользуешь его в другом месте, то всё, твоя проверка в новых местах не сработает, либо же тебе везде придётся добавлять такой 'Ensure' метод

2024-01-02 16:03 UTC, dmytroshchotkin commented on PartsApp/SparePartForm.cs
> +        private void EnsurePhotoDirectoryCreated()
Вместо этого, создай один метод 
который так будет выглядеть:

private void CopyFileSafely(string sourceFilePath, string destinationFilePath)
        {
            try
            {
                string directoryPath = Path.GetDirectoryName(destinationFilePath);
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                System.IO.File.Copy(sourceFilePath, destinationFilePath);
            }
            catch(Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred while copying '{sourceFilePath}' into '{destinationFilePath}':\n{ex.InnerException?.Message ?? ex.Message}"); //Изменим консоль на логгирование когда добавим логгер
            }
        }
        
P.S. не знаю почему так коряво код вставился

2024-01-04 11:12 UTC, a-v-dubr commented on PartsApp/SparePartForm.cs
> +            EnsurePhotoDirectoryCreated();
убрала из Load, метод вызывается там, где файл копируется в папку 
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/48b4086e-d48b-4e88-a7cf-875c1499aef9)

![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/546a4242-a25f-40d5-9aff-739701d77e36)

2024-01-04 11:13 UTC, a-v-dubr commented on PartsApp/SparePartForm.cs
> +        private void EnsurePhotoDirectoryCreated()
добавила метод

2024-01-06 21:55 UTC, dmytroshchotkin commented on PartsApp/SparePartForm.cs
> +            EnsurePhotoDirectoryCreated();
и зачем тебе отдельная папка тут?)
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/36db43e2-99d3-488f-bbdf-c37c32d9c449)
Отдельная папка как раз можеть быть для репозиториев.
Только не миксуй это в один коммит.
В этом коммите, просто вынеси этот Хэлпер на уровень выше.
А отдельным коммитом можешь добавить перенос репозиториев в свою папку Repositories.

2024-01-06 22:40 UTC, dmytroshchotkin requested changes

2024-01-06 22:40 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> -<<<<<<< HEAD
Это ещё что за хрень?
Исправь свой предыдущий коммит, чтобы этого вообще там не было.

2024-01-06 22:40 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +            EditEmployee = editEmployee;
Вертай всё взад.
Что это за внезапное и не нужное изменение?
Ты снаружи и так знаешь с каким employee ты работаешь, зачем тебе public св-во?

2024-01-06 22:40 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void ReplaceSelectedEmployeeDataAfterEditing()
Ну что за название такое?
Не знает метод ни после ни до чего он будет вызываться. Да и с точки зрения этого метода, какая в этом вообще необходимость? Он просто что-то добавляет в список, вот и называться должен именно по смыслу того что он делает.

2024-01-06 22:40 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                OnEmployeesCheckBoxesCheckedChanged(null, null);
Ну это же ужасно, разве не видешь? Тут столько сигналов о том что это плохое решение.
1) 2 null параметра
2) в контексте этого метода, как мне понять, что тут происходит? у меня нет шанса это сделать кроме как идти внутрь этого метода.

И ещё одно правило, применимое вообще во всех случаях, но это хороший пример. Сущности одного уровня не должны вызывать друг друга.
В данном случая один обработчик события не может вызывать другой.
Обработчик события может вызываться только снаружи, т.е. самим фрэймворком.
Вынеси то что тебе нужно в отдельный приватный метод и вызывай в двух хэндлерах.

2024-01-06 22:40 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                _selectedEmployee = editingForm.EditEmployee;
Зачем тут это действие? Это же ровно тот же самый объект.

2024-01-07 21:21 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> -<<<<<<< HEAD
убрала в первый коммит

2024-01-07 21:22 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +            EditEmployee = editEmployee;
вернула. 
факап был здесь 
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/1079d624-ec37-4da5-8c64-b3bfc696890b)

2024-01-07 21:23 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                _selectedEmployee = editingForm.EditEmployee;
убрала

2024-01-07 21:23 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                OnEmployeesCheckBoxesCheckedChanged(null, null);
исправила

2024-01-07 21:23 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void ReplaceSelectedEmployeeDataAfterEditing()
оказался не нужен совсем, удалила

2024-01-07 21:30 UTC, a-v-dubr commented on PartsApp/SparePartForm.cs
> +            EnsurePhotoDirectoryCreated();
сделала

2024-01-08 03:54 UTC, dmytroshchotkin requested changes

2024-01-08 03:54 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +        private void UpdateEditingEmployeeProperties(Employee employee)
а почему эти изменения в этом коммите? Как это относится к задаче?

2024-01-08 03:54 UTC, dmytroshchotkin commented on Infrastructure/Storage/SparePartRepository.cs
> -namespace Infrastructure.Storage
Это изменение должно быть не в этом коммите

2024-01-08 03:54 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +        private readonly Employee _editEmployee;
вот верни вточности как было, чтобы git не показывал изменение. Человек который проверяет не должен тратить время на то что не несёт никакого смысла. Как минимум это отвлекает внимания от цели самого коммита, и также всаёт вопрос а в чём его цель, и это всё тратит время.

2024-01-08 03:54 UTC, dmytroshchotkin commented on Infrastructure/Storage/SparePartRepository.cs
> +        public const string PhotoFolder = @"Товар\";
Приведи причины для выноса этих констант в классы Репозиториев.

2024-01-08 03:54 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +using System.Runtime.InteropServices;
Это ещё что за using??

2024-01-08 04:01 UTC, dmytroshchotkin commented
И ещё у тебя тут "висяк" с предыдущего PR
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/5fa20676-d562-44ce-85da-18f6b419f028)

2024-01-08 19:41 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +        private void UpdateEditingEmployeeProperties(Employee employee)
в позапрошлой версии в БД обновлялся другой объект. думаю, можно оставить в этом коммите, поскольку правильность использования объекта _editEmployee в родительской форме (EmployeeOperationsInfoForm) и была задачей этого bug fix'а
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/1bdfebfe-be5e-46dc-8c34-582fe0084c57)

2024-01-08 20:28 UTC, a-v-dubr commented on Infrastructure/Storage/SparePartRepository.cs
> +        public const string PhotoFolder = @"Товар\";
ты прав, к хранению в БД они отношения не имеют. переношу в FilesStorageHelper

2024-01-08 21:40 UTC, a-v-dubr commented
> И ещё у тебя тут "висяк" с предыдущего PR ![image](https://private-user-images.githubusercontent.com/35776934/294810149-5fa20676-d562-44ce-85da-18f6b419f028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTAyODUsIm5iZiI6MTcwNDc0OTk4NSwicGF0aCI6Ii8zNTc3NjkzNC8yOTQ4MTAxNDktNWZhMjA2NzYtZDU2Mi00NGNlLTg1ZGEtMThmNmI0MTlmMDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDIxMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ODdhOWFmOWYwMzM0ZmFhY2QxNjM2MGVmMDNmMjhhNmQwMTE0YTE1MDkxMzBlYzk1YWQ3OTRkZjU2NDZmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZxVqk1GLVx-CBBbLTLAvZ7USvemQNApeHy0r9LT7II)

удалила

2024-01-08 21:40 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +using System.Runtime.InteropServices;
удалила

2024-01-08 21:41 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +        private readonly Employee _editEmployee;
исправила

2024-01-08 21:41 UTC, a-v-dubr commented on Infrastructure/Storage/SparePartRepository.cs
> -namespace Infrastructure.Storage
убрала изменение

2024-01-09 02:25 UTC, dmytroshchotkin requested changes

2024-01-09 02:25 UTC, dmytroshchotkin commented on Infrastructure/Storage/FilesStorageHelper.cs
> +        public const string EmployeesPhotoDirectory = @"Сотрудники\";
Нет нет нет и ещё раз нет. Ну причём тут этот хэлпер и константные значения конкретных папок?
Если не ошибаюсь, то изначально это было в соответствующих формах, вот там оно и должно оставаться, т.к. там содержится и много логики сейчас.
А те же репозитории, тоже не знают ни о каких папках, там мы просто имеем string содержащий путь к папке и всё на этом.

2024-01-09 02:25 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +        private void UpdateEditingEmployeeProperties(Employee employee)
Я немного не улавливаю связи, но в конечно счёте, тебе решать, так что Ок.

2024-01-09 02:25 UTC, dmytroshchotkin commented on Infrastructure/Storage/Repositories/CustomerRepository.cs
а где в этом коммите изменение namespace-ов в местах которые используют реп-рии?

2024-01-09 17:10 UTC, a-v-dubr commented on Infrastructure/Storage/Repositories/CustomerRepository.cs
неймспейсы не изменились
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/52d5bf1c-3b44-42a4-a8c8-740bff58e522)

2024-01-09 17:29 UTC, a-v-dubr commented on Infrastructure/Storage/FilesStorageHelper.cs
> +        public const string EmployeesPhotoDirectory = @"Сотрудники\";
вернула в формы

2024-01-10 02:21 UTC, dmytroshchotkin commented on Infrastructure/Storage/Repositories/CustomerRepository.cs
Так а изменение namespace то где? Папку новую создала, значит и namespace поменяй на Infrastructure.Repositories

2024-01-10 04:17 UTC, a-v-dubr commented on Infrastructure/Storage/Repositories/CustomerRepository.cs
исправила

2024-01-12 02:21 UTC, dmytroshchotkin approved these changes

2024-01-12 07:28 UTC, merged