Unblock dismissed Employee option
dmytroshchotkin/TruckTir pull request #20
Opened 2024-01-04 19:39 UTC by a-v-dubr

2024-01-10 02:36 UTC, dmytroshchotkin commented
Ну ты зачем заново изобретаешь велосипед? Ничего нам такого не надо
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/e079cb6d-7a67-47a9-b25f-a594669df00b)
Вообще не надо никакой формы дополнительной, просто дополнительный пункт в контекстном меню и один стандартный(!) MessageBox для подтверждения

2024-01-10 02:41 UTC, dmytroshchotkin commented
Добавь ещё одну US и сделай текущую её predecessor-ом. Сторя "add Password reset functionality" и в описание добавь 2 кейса: 1) Админ может сбросить пароль не админу   2) Пароль сбрасывается при восстановлении доступа

2024-01-10 21:44 UTC, a-v-dubr commented
> Ну ты зачем заново изобретаешь велосипед? Ничего нам такого не надо ![image](https://private-user-images.githubusercontent.com/35776934/295414214-e079cb6d-7a67-47a9-b25f-a594669df00b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTUxMjYsIm5iZiI6MTcwNDkxNDgyNiwicGF0aCI6Ii8zNTc3NjkzNC8yOTU0MTQyMTQtZTA3OWNiNmQtN2E2Ny00N2E5LWIyNWYtYTU5NDY2OWRmMDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE5MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjlhNjBlMDA5NGI0ZGNhMTQ3Y2EwNTljOTBhMjVkZTRmNTQ0NTMxNzI1NDQ4MWY1YjFmYTI3MzQ1ZDZiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ju93CB1lxcaoMwq2AZcEpsLHbEuwpYYHWW2quVD1v0Q) Вообще не надо никакой формы дополнительной, просто дополнительный пункт в контекстном меню и один стандартный(!) MessageBox для подтверждения

исправила

2024-01-10 22:01 UTC, a-v-dubr commented
> Добавь ещё одну US и сделай текущую её predecessor-ом. Сторя "add Password reset functionality" и в описание добавь 2 кейса: 1) Админ может сбросить пароль не админу 2) Пароль сбрасывается при восстановлении доступа

добавила

2024-01-12 02:50 UTC, dmytroshchotkin requested changes

2024-01-12 02:50 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    $"\nУволен {_selectedEmployee.DismissalDate?.ToString("d")}",
чё за детские ошибки тут?
где двоеточия после "принят на работу" и "уволен"

2024-01-12 02:50 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    MessageBoxDefaultButton.Button2);
Ты правда подумала что это хорошая идея этот кусок оставить прям тут в методе? вынеси в приватный же ну 'ShowEnableUserMessageBox'

2024-01-12 02:50 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void OnUnblockOptionClick(object sender, EventArgs e)
Должна же быть какая-то логическая последовательность в названии методов.
если этот называется 'unblock' значит противоположный ему должен был называться 'block' а у тебя он 'Dismiss'.
Поменяй в коде везде на 'Enable'

2024-01-12 02:50 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void OnUnblockOptionClick(object sender, EventArgs e)
отдельным [refactoring] коммитом переименуй 'dismiss' на 'disable'. Везде в коде. Единственное не меняй на UI, там нам не важно как будет называться 'заблокировать' или 'уволить', но в коде мы будем пользоваться стандартно принятыми 'enable' и 'disable'.
P.S. вообще это плохо когда названия в коде расходятся с UI-ными (бизнесовыми терминами), но в нашем случае ещё и разность языков, так что ладно.

2024-01-12 12:40 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    $"\nУволен {_selectedEmployee.DismissalDate?.ToString("d")}",
добавила

2024-01-12 12:41 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +                    MessageBoxDefaultButton.Button2);
исправила

2024-01-12 12:42 UTC, a-v-dubr commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void OnUnblockOptionClick(object sender, EventArgs e)
переименовала unblock и отдельным коммитом disable (только для объектов, в БД остаётся атрибут DismissalDate)

2024-01-13 17:26 UTC, dmytroshchotkin commented on PartsApp/EmployeeOperationsInfoForm.cs
> +        private void OnUnblockOptionClick(object sender, EventArgs e)
Это не очень хорошо, но ок

2024-01-13 17:27 UTC, dmytroshchotkin approved these changes
Единственное ещё, убери это окно, оно не нужно
![image](https://github.com/dmytroshchotkin/TruckTir/assets/35776934/1ab099fc-2b4c-4450-b83a-eccf4d2b931d)

2024-01-13 20:55 UTC, a-v-dubr commented
> Единственное ещё, убери это окно, оно не нужно ![image](https://private-user-images.githubusercontent.com/35776934/296506175-1ab099fc-2b4c-4450-b83a-eccf4d2b931d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzk1MzUsIm5iZiI6MTcwNTE3OTIzNSwicGF0aCI6Ii8zNTc3NjkzNC8yOTY1MDYxNzUtMWFiMDk5ZmMtMmI0Yy00NDUwLWI4M2EtZWNjZjRkMmI5MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIwNTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OTc1OTM4Y2VmMDE0ZTNhOTI0YmExNGY4ZjJhYTFlN2QwYTk5MzNkZDk2NmQ4YTBlNjAwZmZhOTYzNTg5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.COOrt8rP44lxN7nyua_AZd_Jbjtcg4la2YI91ZyOsNE)

убрала

2024-01-13 20:56 UTC, merged