#14 Added check for SpareParts availability before creating Sale
dmytroshchotkin/TruckTir pull request #24
Opened 2024-04-22 04:40 UTC by a-v-dubr

2024-04-24 00:29 UTC, dmytroshchotkin requested changes

2024-04-24 00:29 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +                        DisplayInvalidAvailabilityMessageBox(sp);
каким образом действие на UI находится в простецком методе кот. возв-ет bool?

2024-04-24 00:29 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +        private List<DataGridViewRow> GetRowsOfSparePartsWithChangedAvailability(List<SparePart> spList)
Этот метод просто возвращает rows для соотв-щих spare parts. Откуда внутри этого метода знание о том что это "ChangedAvailability" или "rowsToRemove" ?

2024-04-24 00:29 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +                var sparePartsWithChangedAvailabilities = GetSparePartsWithChangedAvailability();
Внутри нашего "домена", т.е. программы, мы можем исп-ть сокращение SPs для SpareParts

2024-04-24 00:29 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +            foreach (var sp in spList)
Мы же обговорили это. Это не нормальный подход показывать 150 message box-ов. 
Соедини весь текст и выведи в однои box-е

2024-04-24 00:29 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +            if (e.Button == MouseButtons.Left && IsRequiredFieldsValid())
Не надо миксовать это .
Сделай по-другому 
if (e.Button != MouseButtons.Left)
{
    return;
}

..........

2024-04-25 04:26 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +                        DisplayInvalidAvailabilityMessageBox(sp);
исправила

2024-04-25 04:26 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +        private List<DataGridViewRow> GetRowsOfSparePartsWithChangedAvailability(List<SparePart> spList)
исправила

2024-04-25 04:26 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +                var sparePartsWithChangedAvailabilities = GetSparePartsWithChangedAvailability();
применила сокращения

2024-04-25 04:27 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +            foreach (var sp in spList)
сделала один mb

2024-04-25 04:27 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +            if (e.Button == MouseButtons.Left && IsRequiredFieldsValid())
исправила

2024-04-25 12:25 UTC, dmytroshchotkin requested changes

2024-04-25 12:25 UTC, dmytroshchotkin commented on PartsApp/SaleForm.cs
> +            foreach (var sp in spList)
отписал в личку по стилю

2024-04-25 18:10 UTC, a-v-dubr commented on PartsApp/SaleForm.cs
> +            foreach (var sp in spList)
> отписал в личку по стилю

исправила

2024-04-28 02:27 UTC, dmytroshchotkin approved these changes

2024-04-28 07:50 UTC, merged