#35 Prevent duplicate of Returns
dmytroshchotkin/TruckTir pull request #31
Opened 2024-05-01 09:14 UTC by a-v-dubr

2024-05-04 12:52 UTC, dmytroshchotkin requested changes

2024-05-04 12:52 UTC, dmytroshchotkin commented on PartsApp/ReturnForm.cs
> +                var fullOperationDetail = sale.OperationDetailsList.First(od => od.SparePart.SparePartId == returnOperationDetail.SparePart.SparePartId);
Ты знаешь в чём разница First и FirstOrDefault?

2024-05-04 12:52 UTC, dmytroshchotkin commented on PartsApp/ReturnForm.cs
> +using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
убери

2024-05-04 12:52 UTC, dmytroshchotkin commented on PartsApp/ReturnForm.cs
> +            var checkSale = PartsDAL.FindSale(_sale.OperationId);
я уже говорил какой префикс принято исп-ть

2024-05-04 12:52 UTC, dmytroshchotkin commented on PartsApp/ReturnForm.cs
> +                    int rowIndex = ReturnDGV.Rows.Cast<DataGridViewRow>().First(r => r.DataBoundItem == odWithChangedCount).Index;
А ты в курсе что ты делаешь Cast всей таблицы на каждой итерации цикла? В нашем случае это простительно, но ты должна такое замечать, как минимум.

2024-05-04 12:52 UTC, dmytroshchotkin commented on PartsApp/ReturnForm.cs
> +            {
код по-прежнему оч. плохо читаем. Как минимум, всё содержимое foreach можно вынести в отд. метод.

2024-05-05 09:43 UTC, a-v-dubr commented on PartsApp/ReturnForm.cs
> +using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
удалено в коммите 113836a

2024-05-05 09:44 UTC, a-v-dubr commented on PartsApp/ReturnForm.cs
> +                var fullOperationDetail = sale.OperationDetailsList.First(od => od.SparePart.SparePartId == returnOperationDetail.SparePart.SparePartId);
First выбрасывает исключение, если элемент не найден, FirstOrDefault возвращает null. 
Заменила на Find (метод List, к-рый работает аналогично FirstOrDefault для IEnumerable)

2024-05-05 10:47 UTC, a-v-dubr commented on PartsApp/ReturnForm.cs
> +                    int rowIndex = ReturnDGV.Rows.Cast<DataGridViewRow>().First(r => r.DataBoundItem == odWithChangedCount).Index;
исправила

2024-05-05 19:43 UTC, a-v-dubr commented on PartsApp/ReturnForm.cs
> +            {
исправила

2024-05-05 20:38 UTC, a-v-dubr commented on PartsApp/ReturnForm.cs
> +            var checkSale = PartsDAL.FindSale(_sale.OperationId);
исправила на original

2024-05-11 14:32 UTC, dmytroshchotkin approved these changes

2024-05-11 20:36 UTC, merged