Add domain project
dmytroshchotkin/TruckTir pull request #4
Opened 2023-10-23 22:41 UTC by a-v-dubr

2023-10-24 23:54 UTC, dmytroshchotkin requested changes

2023-10-24 23:54 UTC, dmytroshchotkin commented on Models/Models.Operations/Sale.cs
> +        public void TrySetOperationDetails(Lazy<IList<OperationDetails>> operationDetails)
Зачем этот метод?

2023-10-24 23:54 UTC, dmytroshchotkin commented on Models/Models.Users/ContactInfo.cs
что значит Models.Users и чем это лучше чем то что было?

2023-10-24 23:54 UTC, dmytroshchotkin commented on Models/Models.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
почему 2-я версия только? Там же самая большая это 2.1

2023-10-24 23:54 UTC, dmytroshchotkin commented on Models/bin/Debug/netstandard2.0/Models.deps.json
ничего тебя не смутило с этим файлом? =)

2023-10-24 23:54 UTC, dmytroshchotkin commented on Models/bin/Debug/netstandard2.0/Models.dll
и с этим тоже)

2023-10-24 23:54 UTC, dmytroshchotkin commented on PartsApp/AddEmployeeForm.cs
> +using static Models.Helper.PropertiesHelper;
если что-то существует в языке это ещё не значит что это нужно обязательно использовать =)

2023-10-24 23:54 UTC, dmytroshchotkin commented on PartsApp/PartsDAL.cs
> +            result.TrySetOperationDetails(new Lazy<IList<OperationDetails>>(() => PartsDAL.FindSaleDetails(result)));
посмотри что делает и как используется класс Lazy. И скажи нужен ли он тогда здесь?

2023-10-25 21:22 UTC, a-v-dubr commented on Models/Models.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
получила ошибку при попытке изменить на standard 2.1 
![image](https://github.com/dmytroshchotkin/TruckTir/assets/101408863/0c5b696a-d4cd-4402-8f66-1aa05cdcb0c0)

2023-10-25 21:41 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +using static Models.Helper.PropertiesHelper;
убрала

2023-10-26 21:43 UTC, a-v-dubr commented on Models/Models.Operations/Sale.cs
> +        public void TrySetOperationDetails(Lazy<IList<OperationDetails>> operationDetails)
чтобы убрать обращение к БД внутри конструктора. пока оставила в том же виде для Purchase, Sale, SparePart

upd: в Employee удалила поле Lazy<ContactInfo>

2023-10-26 21:43 UTC, a-v-dubr commented on Models/Models.Users/ContactInfo.cs
переименовала в Models.Contacts

2023-10-26 21:44 UTC, a-v-dubr commented on Models/bin/Debug/netstandard2.0/Models.deps.json
удалила файл и обновила гитигнор

2023-10-26 21:44 UTC, a-v-dubr commented on Models/bin/Debug/netstandard2.0/Models.dll
удалила файл и обновила гитигнор

2023-10-26 21:44 UTC, a-v-dubr commented on PartsApp/AddEmployeeForm.cs
> +using static Models.Helper.PropertiesHelper;
убрала везде

2023-10-26 21:47 UTC, a-v-dubr commented on PartsApp/PartsDAL.cs
> +            result.TrySetOperationDetails(new Lazy<IList<OperationDetails>>(() => PartsDAL.FindSaleDetails(result)));
временно оставляю для свойств Purchase, Sale, SparePart, т.к. поля этого типа инициализировались во всех к-рах

2023-11-01 22:35 UTC, dmytroshchotkin approved these changes

2023-11-01 22:37 UTC, merged