Add repositories
dmytroshchotkin/TruckTir pull request #9
Opened 2023-11-12 18:42 UTC by a-v-dubr

2023-11-14 03:42 UTC, dmytroshchotkin requested changes

2023-11-14 03:42 UTC, dmytroshchotkin commented on Infrastructure/Storage/PropertiesHandlers/AvailabilityHandler.cs
> +    internal static class AvailabilityHandler
почему называется Handler?

2023-11-14 03:42 UTC, dmytroshchotkin commented on Models/Models.Contacts/Employee.cs
> +                   photo, note, passportNum, title, accessLayer, login, password, new ContactInfo())
такс, чёто не понял, когда это мы так решили сделать?

2023-11-14 21:55 UTC, a-v-dubr commented on Infrastructure/Storage/PropertiesHandlers/AvailabilityHandler.cs
> +    internal static class AvailabilityHandler
переименовала в DatabaseHandler. а папке PropertiesHandlers временно лежат классы с методами для value objects, которые пока не получилось поместить внутри соотв. репозиториев. название выбрано потому, что обновление объектов ContactInfo и Availability происходит только внутри методов этих стат. классов (за исключением двух private методов FindContactInfo в CustomerRepository и SupplierRepository). 

методы для ContactInfo однотипно используются в CustomerRepository, SupplierRepository, EmployeeRepository, и после обновления версии приложения вместо этого стат. класса будет интерфейс с имплементацией по дефолту.

с Availability не до конца понимаю что делать. свойство List<Availability> - dependency для класса SparePart, при этом изменения в объектах Availability происходят в методах классов IOperation плюс есть вызываемый в форме метод, который перезаписывает данные в БД не в контексте методов для SparePart или IOperation. мне кажется, методы для Availability скорее представляют бизнес-логику и по крайней мере часть их я бы вынесла из Infrastructure и Presentation.

2023-11-14 21:55 UTC, a-v-dubr commented on Models/Models.Contacts/Employee.cs
> +                   photo, note, passportNum, title, accessLayer, login, password, new ContactInfo())
это ошибка. вернула как было

2023-11-15 01:15 UTC, dmytroshchotkin commented on Infrastructure/Storage/PropertiesHandlers/AvailabilityHandler.cs
> +    internal static class AvailabilityHandler
Да, с availability будем что-то делать скоро. Мне не нравится этот класс вообще.

2023-11-15 01:22 UTC, dmytroshchotkin approved these changes

2023-11-15 08:08 UTC, merged